# Generated by Django 4.2.4 on 2023-08-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidbeck', '0002_rename_blog_fidbeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidbeck',
            name='preview',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
    ]
