# Generated by Django 4.2.4 on 2023-08-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidbeck', '0003_alter_fidbeck_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidbeck',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fidbeck',
            name='views_count',
            field=models.ImageField(default=0, upload_to='', verbose_name='просмотры'),
        ),
    ]
