# Generated by Django 4.2.4 on 2023-08-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidbeck', '0004_alter_fidbeck_is_published_alter_fidbeck_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidbeck',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
