# Generated by Django 4.2.4 on 2023-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidbeck', '0005_alter_fidbeck_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidbeck',
            name='content',
            field=models.TextField(unique=True, verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='fidbeck',
            name='preview',
            field=models.ImageField(blank=True, unique=True, upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='fidbeck',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
