# Generated by Django 4.2.4 on 2023-08-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_blog_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
