# Generated by Django 4.2.7 on 2023-12-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default=True, verbose_name='опубликовано'),
        ),
    ]
