# Generated by Django 4.2.7 on 2023-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.CharField(choices=[('yes', 'Активна'), ('no', 'Не активна')], default=False, verbose_name='опубликовано'),
        ),
    ]
