# Generated by Django 4.2.7 on 2023-12-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_change_product', 'Can_change_product')], 'verbose_name': 'Расслыка'},
        ),
    ]
